Repository Jan0707/phpstan-prophecy, pull requests merged in 2020-05, with the labels that each got.

#169 Fix: Rename workflow
  .github/workflows/integrate.yml
  README.md
Labels: bug

#170 Enhancement: Require ergebnis/license:^1.0.0
  composer.json
  composer.lock
Labels: dependency

#171 Fix: Specify patch version as well
  composer.json
  composer.lock
Labels: bug

#172 Enhancement: Run builds with different versions of phpunit/phpunit
  .github/workflows/integrate.yml
Labels: enhancement

#173 Fix: Run static analysis with locked dependencies
  .github/workflows/integrate.yml
Labels: bug

#174 Enhancement: Run build with phpunit/phpunit:^8.0.0
  .github/workflows/integrate.yml
  composer.json
  composer.lock
Labels: enhancement

#175 Fix: Include phpunit/phpunit version in cache key
  .github/workflows/integrate.yml
Labels: bug

#176 Fix: Remove deprecated --no-suggest option
  .github/workflows/integrate.yml
  Makefile
Labels: bug

#177 Enhancement: Run build with phpunit/phpunit:^9.0.0
  .github/workflows/integrate.yml
  composer.json
  composer.lock
Labels: enhancement

#178 Fix: Add missing semicolon
  README.md
Labels: bug

#165 Use generics
  .php_cs
  CHANGELOG.md
  composer.json
  composer.lock
  extension.neon
  src/PhpDoc/ObjectProphecy/TypeNodeResolverExtension.php
  src/Type/ObjectProphecy/ObjectProphecyType.php
  src/Type/ObjectProphecy/RevealDynamicReturnTypeExtension.php
  src/Type/ObjectProphecy/WillExtendOrImplementDynamicReturnTypeExtension.php
  src/Type/Prophet/ProphesizeDynamicReturnTypeExtension.php
  stubs/ObjectProphecy.phpstub
  stubs/ProphecyInterface.phpstub
Labels: enhancement

#182 Fix: Remove symbolic link
  CHANGELOG.md
  README.md
  src/extension.neon
Labels: bug

#183 Fix: Reference
  CHANGELOG.md
Labels: bug
